### ISSUE TITLE
Zitate

### ISSUE THREAD

**Issue by Byteingpython** [SlimeCloud/java-SlimeBot#110]
**Is your feature request related to a problem? Please describe.**
Ein reiner Zitate Textchannel ist schwer zu moderieren und für die user ist es kompliziert zitate einzusenden

**Describe the solution you'd like**
Es wäre praktisch, wenn man nachrichten rechtsklicken könnte, um sie vom bot in den zitate channel schicken zu lassen. Der bot könnte dann auch direkt per dm nachfragen, ob das für den verfasser der nachricht klargeht. Externe Zitate könnte man per modal einschicken

**ToDos**
A todo list for fixing the error
- [ ] Rechtsklick command machen
- [ ] slash command mit modal für externe Zitate hinzufügen

**Describe alternatives you've considered**
Es bei einem Textchannel belassen

**Additional context**

**Comment by MatitoDA** [comment]
Please leave out the DM notification, I think it should be enough to mark the quoted person in the message.
Maybe there would be a solution that when the quoted person deletes their message, the message in quote channel is also deleted. (?)
"External" quotes are forbidden anyway. For quotes from voice channels, I would make a command, e.g. /quote <user> <quote>.
There would be only the question whether we make the quote channel message locked, because everything goes about commands, but not all will check. (stupid kids xD)

As a feature, I would appreciate it if there is a link to the quote
